global using CommunityToolkit.Mvvm.ComponentModel;
global using CommunityToolkit.Mvvm.Input;
global using DragDropMAUIDemo.Model;
global using DragDropMAUIDemo.ViewModel;
global using DragDropMAUIDemo.View;
global using System.Collections.ObjectModel;
global using System.ComponentModel;
global using System.Diagnostics;
global using System.Runtime.CompilerServices;